### ISSUE TITLE
Hide cell after card is moved

### ISSUE THREAD

**Issue by Rwhytsell** [st01k/Freecell-DS-F16#17]
I have noticed in the filler move that, when the card is moved onto the freecell, the card that is moved is not removed from the playing cell that it originated. 

Null pointer happens if you try to set the JLabels icon to null.

**Comment by Rwhytsell** [comment]
This may also be an issue with the filler moves

**Comment by st01k** [comment]
see issue #13 
i believe this is the same thing.  let's move your notes from here into there.

**Comment by st01k** [comment]
yea, i believe this was the filler move.  either way, gone now.
