### ISSUE TITLE
hint button action in gui

### ISSUE THREAD

**Issue by st01k** [st01k/Freecell-DS-F16#19]
what should the hint button do in gui?

**Comment by st01k** [comment]
i'm leaning towards a card/cell highlight/dim effect.

**Comment by st01k** [comment]
guys, need some input on this.

**Comment by brandonlwharton** [comment]
i think a cell highlight,though i have seen other games dim everything but the hints

**Comment by Rwhytsell** [comment]
We could do highlighting or something with the console.

**Comment by st01k** [comment]
yea, i had thought about listing moves in the console, too... but i like the highlighting/dimming best.  made issue #26 based on what we've all talked about.  gonna close this out, and we can talk about it in there.
