### ISSUE TITLE
solver patterns

### ISSUE THREAD

**Issue by st01k** [st01k/Freecell-DS-F16#20]
patterns for the solver to check available moves against to prioritize solution searches.

**Comment by st01k** [comment]
getAllMoves in board is functional.  the turn creates the solver and gives it the board, so just grab it from there, and call the method to test your patterns.

**Comment by brandonlwharton** [comment]
Since you called a halt on the solver i am going to check this off

**Comment by st01k** [comment]
ok.  you mentioned that you might still work on the solver.  you still planning on doing that?
