### ISSUE TITLE
paperwork updates

### ISSUE THREAD

**Issue by st01k** [st01k/Freecell-DS-F16#21]
by tuesday, 6 Dec

- [x] update functional/technical requirements document

- [x] update all diagrams with a fine-toothed comb, including parameters for methods in UML.

**Comment by brandonlwharton** [comment]
I'll get on that

**Comment by st01k** [comment]
changed the date on that.  pushed it out a week.

**Comment by brandonlwharton** [comment]
UML and ERD done
