### ISSUE TITLE
hint action in gui

### ISSUE THREAD

**Issue by st01k** [st01k/Freecell-DS-F16#26]
- [x] implemented

data for hint action in gui (should be passed into gui when button is pressed): 
engine will call on board to generate the info from the hint method.
- keys to all moveable cards

- [x] implemented

- highlight/darken cards that can be moved

**Comment by st01k** [comment]
was looking through this hint stuff... i think it's gonna be quicker and easier (since we only have 4 more days) to just highlight/dim the cards that can move at any given turn.  so, i'm going to add the method getHint into board that just returns a list of keys.  how does that sound?

**Comment by st01k** [comment]
instead of putting it in board, i just incorporated it into hint in Engine.  just needs implemented in `HintBtnActionPerformed` in FreeGUI

**Comment by Rwhytsell** [comment]
The plan for this is to pass in key(s) and dim the corresponding cards correct?

**Comment by st01k** [comment]
yea, the keys are already in there @2144 `HintBtnActionPerformed`

**Comment by st01k** [comment]
card highlights are implemented.  still needs to be tested in winblows
