### ISSUE TITLE
timer in gui

### ISSUE THREAD

**Issue by st01k** [st01k/Freecell-DS-F16#27]
- [x] implemented
- [x] integrated

Arnold Schwarzenegger voice... let's doooo eeeet!

**Comment by brandonlwharton** [comment]
gotcha

**Comment by brandonlwharton** [comment]
I could use some guidance on integrating this into the gui

**Comment by Rwhytsell** [comment]
Check slack

**Comment by st01k** [comment]
welp, it's in there.  the hours aren't displaying properly.  so, i just removed the hour display for now.
